spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/piickle
      username: root
      password: rkdudmysql4_
  data.mongodb:
    uri: mongodb://localhost:27017/local?tls=false&retryWrites=true&w=majority
