server:
  port: 8081

logging:
  level:
    org.hibernate.type.descriptor.sql: trace

cloud:
  aws:
    s3:
      bucket: piiklebucket11
    credentials:
      accessKey: AKIAUBQNOB62TWHQS35O
      secretKey: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

jwt:
  header: Authorization
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
  token-validity-in-seconds: 86400

spring:
  messages:
    basename: messages
  jpa:
    hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

---

spring:
  config:
    activate:
      on-profile: dev

---

spring:
  config:
    activate:
      on-profile: ky

---

spring:
  config:
    activate:
      on-profile: dh