server:
  port: 8081

logging:
  level:
    org.hibernate.type.descriptor.sql: trace

jwt:
  header: Authorization
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
  token-validity-in-seconds: 86400

spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: com.team.piickle.config.CamelCaseToUnderscoresWithUpperCasesNamingStrategy

---

spring:
  config:
    activate:
      on-profile: dev

---

spring:
  config:
    activate:
      on-profile: ky

---

spring:
  config:
    activate:
      on-profile: dh